### Create a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "testuserv1@gmail.com",
    "password": "My_test_password@123",
    "name": "Test User v1"
}


### Login a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "testuserv2@gmail.com",
    "password": "My_test_password@123"
}


### Find a particular user w/ id
GET http://localhost:3000/auth/3 


### Find users with a given email
GET http://localhost:3000/auth?email=test@test.com


### Delete a user w/ a given id
DELETE http://localhost:3000/auth/1


### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "password": "testified@testify.com"
}